map.width=10
map.height=10
fillPercentage=0.4
fillPercent=40
herbivore.health=10
herbivore.speed=1
herbivore.satiety=10
predator.health=10
predator.speed=1
predator.satiety=10
predator.damage=1
wolfsNumber=8
rabbitsNumber=8
grassNumber=8